### PR TITLE
Patch live-activity PR - copy all js files as one layer

### PR DESCRIPTION
**Pull request by bgoncal**

### CODE REVIEW

**Review by jpelgrom — APPROVED** [review]
Thanks for the quick check and fix 🙏

**Comment by jpelgrom** [comment]
For future reference: patches failed deployment after merging #309 with error

```
node:internal/modules/cjs/loader:1503
  throw err;
  ^

Error: Cannot find module './live-activity.js'
Require stack:
- /app/legacy.js
- /app/webapp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1500:15)
    ...
    at Object.<anonymous> (/app/legacy.js:4:22)
```

https://discord.com/channels/330944238910963714/1517983662577156327
